#!/bin/sh
#bash commands here


curl -o - --http1.1 --include \
     --no-buffer \
     --header "Connection: Upgrade" \
     --header "Upgrade: websocket" \
     --header "Host: ws.vozpreta.com.br" \
     --header "Origin: https://vozpreta.com.br" \
     --header "Sec-WebSocket-Key: isBBekl53e4D/ViPH0+gxQ==" \
     --header "Sec-WebSocket-Version: 13" \
     https://ws.vozpreta.com.br/occupy

if [ "$(curl -sL -w '--no-buffer \
     --header "Connection: Upgrade" \
     --header "Upgrade: websocket" \
     --header "Host: ws.vozpreta.com.br" \
     --header "Origin: https://vozpreta.com.br" \
     --header "Sec-WebSocket-Key: isBBekl53e4D/ViPH0+gxQ==" \
     --header "Sec-WebSocket-Version: 13" \' https://ws.vozpreta.com.br/occupy -o /dev/null)" = "200" ]; then
    echo "Success"
else
    echo "Fail"
fi
